main: main.cpp User.h UserProxy.h VerificationStrategy.h EncryptStrategy.h
	g++ -std=c++11 -o main main.cpp
test: main.cpp User.h UserProxy.h VerificationStrategy.h EncryptStrategy.h
	g++ -g *.cpp *.h -o test.exe
